/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package AgendaDeContatos.view;

import AgendaDeContatos.controler.ClienteRepository;
import AgendaDeContatos.controler.ConexaoMySQL;
import AgendaDeContatos.model.Contatos;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

public class PesquisaDeCliente extends javax.swing.JInternalFrame {
    private static PesquisaDeCliente instancia;
    private TelaAlteracaoClientes telaAlteracaoClientes;
    private TelaInicial telaInicial;

    public PesquisaDeCliente(TelaInicial telaInicial) {
        initComponents();
        this.telaInicial = telaInicial;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JToggleButton();
        btnFechar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setTitle("Alteração de Cadastro");
        setDoubleBuffered(true);
        setVisible(true);

        jLabel1.setText("Para alterar os dados de um usuário, insira o CPF para realizar a busca:");

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btnFechar)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addComponent(btnFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
    ClienteRepository clienteRepository = new ClienteRepository();
    Contatos cliente = clienteRepository.selecionar(txtPesquisa.getText().trim()); // Removido ConexaoMySQL.connection

    if (cliente != null) {
        try {
            telaAlteracaoClientes = TelaAlteracaoClientes.getInstancia(telaInicial);
            
            if (telaAlteracaoClientes != null) {
                telaAlteracaoClientes.setCliente(cliente);

                JDesktopPane desktopPane = telaInicial.getDesktopPane(); // Certifique-se de que este método existe
                if (!desktopPane.isAncestorOf(telaAlteracaoClientes)) {
                    desktopPane.add(telaAlteracaoClientes);
                    telaAlteracaoClientes.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
                }

                telaAlteracaoClientes.setSelected(true);
                telaAlteracaoClientes.setVisible(true);
            } else {
                System.err.println("Erro: telaAlteracaoClientes está nula!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, 
                    "Erro ao abrir a tela de alteração de contatos: " + ex.getMessage(),
                    "Pesquisa de contatos",
                    JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(null, "Contato não encontrado.",
                                      "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        fecharJanela();
    }//GEN-LAST:event_btnFecharActionPerformed
    
        //função para fechar a janela
    private void fecharJanela(){
        instancia = null;
        dispose();
    }
    
    public static PesquisaDeCliente getInstancia(TelaInicial telaInicial) {
    if (instancia == null)
        instancia = new PesquisaDeCliente(telaInicial);
    return instancia;
}
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JToggleButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
